version: '3.3'


services:
  reverse-proxy:
    image: traefik
    command:
      - --defaultentrypoints=https,http
      - --api
      - --api.entryPoint=traefik
      - --api.dashboard=false
      - --debug=false
      - --entryPoints=Name:http Address::80
      - --entryPoints=Name:https Address::443 TLS
      - --logLevel=INFO
      - --accessLog.format=json
      - --docker
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.swarmmode=true
      - --docker.watch=true
      - --docker.exposedbydefault=false
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tmp:/tmp
    networks:
      - traefik-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-net:
    driver: overlay
    external: true

volumes:
  tmp:
