version: '3'

services:

  grafana:
    image: grafana/grafana:latest
    networks:
      - external
      - grafana-net
      - traefik-net
    volumes:
      - grafana_config:/etc/grafana
      - grafana_data:/var/lib/grafana
      - grafana_home:/usr/share/grafana
      - grafana_logs:/var/log/grafana
      - grafana_plugins:/var/lib/grafana/plugins
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:${HOST}"
        traefik.port: 3000
        traefik.docker.network: traefik-net
        traefik.frontend.headers.STSSeconds: 63072000
        traefik.frontend.headers.STSIncludeSubdomains: "true"
        traefik.frontend.headers.STSPreload: "true"


volumes:
  grafana_config:
  grafana_data:
  grafana_home:
  grafana_logs:
  grafana_plugins:
  

networks:
  external:
  traefik-net:
    external: true
  grafana-net:
    external: true

### Environment variables
# HOST