version: '3.4'
services:
  database:
    image: postgres:12
    ports:
     - target: 5432
       published: ${DBPORT}
       protocol: tcp
       mode: host
    volumes:
     - dbdata:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=${DBUSER}
     - POSTGRES_PASSWORD=${DBPASS}
     - POSTGRES_DB=${DBUSER}
     - TZ=Europe/Warsaw

volumes:
  dbdata:

### Environment variables
# DBUSER
# DBPASS
# DBPORT
