version: '3.4'
services:
  ism:
    image: vonproteus/internet-speed-monitor
    environment:
      - INFLUXDATABASENAME=ism
    networks:
      - external
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 31m

  influx:
    image: influxdb
    volumes:
     - data:/var/lib/influxdb 
    environment:
     - INFLUXDB_WRITE_USER=root
     - INFLUXDB_WRITE_USER_PASSWORD=toor
     - INFLUXDB_READ_USER=${DBUSER}
     - INFLUXDB_READ_USER_PASSWORD=${DBPASS}
     - INFLUXDB_DB=ism
    networks:
      - internal
      - grafana-net

volumes:
  data:

networks:
  external:
  internal:
    driver: overlay
    internal: true
  traefik-net:
    external: true
  grafana-net:
    external: true
  
### Environment variables
# DBUSER
# DBPASS
# DBPORT