version: '3.4'
services:
  ism:
    image: vonproteus/internet-speed-monitor
    environment:
      - INFLUXDATABASENAME=ism
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 31m

  influx:
    image: influxdb
    volumes:
     - data:/var/lib/influxdb 
    environment:
     - INFLUXDB_WRITE_USER=root
     - INFLUXDB_WRITE_USER_PASSWORD=toor
     - INFLUXDB_READ_USER=${DBUSER}
     - INFLUXDB_READ_USER_PASSWORD=${DBPASS}
     - INFLUXDB_DB=ism
    ports:
     - target: 8086
       published: ${DBPORT}
       protocol: tcp
       mode: host

volumes:
  data:
  
### Environment variables
# DBUSER
# DBPASS
# DBPORT